version: '3.7'

services:

  #MySQL Service
  avature-mysql:
    container_name: avature-mysql
    image: mysql:5.7.22
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: avature_laravel
      MYSQL_ROOT_PASSWORD: 000000
      MYSQL_USER: develop
      MYSQL_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-config/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - /opt/docker/avature-mysql:/var/lib/mysql/
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      avature:
        ipv4_address: 20.2.0.2

  #MenCached
  avature-memcached:
    container_name: avature-memcached
    image: memcached:latest
    restart: always
    networks:
      avature:
        ipv4_address: 20.2.0.3

  #Nginx Service
  avature-nginx:
    container_name: avature-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9891:80"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      avature:
        ipv4_address: 20.2.0.4

  #PHP Service
  avature-laravel:
    container_name: avature-laravel
    build:
      args:
        user: develop
        uid: 1000
      context: .
      dockerfile: ./docker-config/php/Dockerfile 
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - avature-mysql
      - avature-memcached
      - avature-jobberwocky
    depends_on:
      - avature-nginx
      - avature-mysql
      - avature-memcached
      - avature-jobberwocky
    extra_hosts:   
      - api-avature-jobberwocky.local:20.2.0.6
    networks:
      avature:
        ipv4_address: 20.2.0.5

  #JobberwockyExteneralJobs API
  avature-jobberwocky:
    container_name: avature-jobberwocky
    restart: always
    build:
      context: .
      dockerfile: ./docker-config/jobberwocky-extra-source/Dockerfile 
    command: ['sh', '-c', 'cd /app && node app.js']
    volumes:
      - './jobberwocky-extra-source:/app'
    ports:
      - "8081:8080"
    networks:
      avature:
        ipv4_address: 20.2.0.6

#Volumes
volumes:
  #gateway-mysql:
  dbdata:
    driver: local

#Docker Networks
networks:
  avature:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 20.2.0.0/16